# Generated by Django 4.2.3 on 2023-08-25 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_leaverequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('Sick leave', 'Sick leave'), ('Vacation leave', 'Vacation leave'), ('Travel leave', 'Travel leave'), ('Emergency leave', 'Emergency leave')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
